change bg color
shahednasser/sbuttons pull request #123
Opened 2020-09-14 22:22 UTC by agalakova-m

Changed background color for .sidebar a:before

Issue:
https://github.com/shahednasser/sbuttons/issues/122

2020-09-15 14:46 UTC, shahednasser requested changes

2020-09-15 14:46 UTC, shahednasser commented on assets/css/sidebar.css
> +  background-color: --main-color;
You need to put it in the `var()` function like this: `var(--main-color)`

2020-09-16 09:04 UTC, agalakova-m commented
Oh, my bad. I guess now it's right?

2020-09-16 16:12 UTC, merged

2020-09-16 16:12 UTC, shahednasser commented
Thank you for your work!

@all-contributors please add @agalakova-m for code