close-sidebar fix
shahednasser/sbuttons pull request #127
Opened 2020-09-15 16:36 UTC by esakki-selvaraj

it positions the close icon near the end of sidebar by adjusting the padding

Issue: close #121

2020-09-15 19:33 UTC, shahednasser requested changes

2020-09-15 19:33 UTC, shahednasser commented on assets/css/sidebar.css
> +    padding-right:5px !important;
Is the `!important` for padding right and top necessary? I think it would work without them. Please try and if it doesn't then you can leave them

2020-09-16 02:17 UTC, esakki-selvaraj commented
I had updated it 💯

2020-09-16 16:10 UTC, merged

2020-09-16 16:10 UTC, shahednasser commented
Great work thank you!

@all-contributors please add @esakki-selvaraj for code and bug