feat: add a link to submit new button ideas
shahednasser/sbuttons pull request #152
Opened 2020-09-20 05:40 UTC by markkulube

Added a link to submit new button ideas in index.html

Issue: #135

2020-09-20 08:59 UTC, shahednasser requested changes

2020-09-20 08:59 UTC, shahednasser commented on index.html
> +                target="blank">here</a>.
this should be `target="_blank"`

2020-09-20 16:32 UTC, markkulube commented on index.html
> +                target="blank">here</a>.
@shahednasser - done!

2020-09-21 20:46 UTC, merged

2020-09-21 20:47 UTC, shahednasser commented
Great thank you!

@all-contributors please add @markkulube for code