feat: add more explanation in the "How to Use" section #149
shahednasser/sbuttons pull request #159
Opened 2020-09-21 10:41 UTC by salonigoyal2309

Issue: #149
If you want any other changes please let me know :)

2020-09-21 20:44 UTC, shahednasser requested changes

2020-09-21 20:44 UTC, shahednasser commented on README.md
> +For using sButtons in your code , just add the classes of sButton you want to either  ```<button>``` or ```<a>``` tags :
Please replace "For using sButtons in your code" with "To use sButtons in your project. (Make the change in `index.html` as well

2020-09-21 20:44 UTC, shahednasser commented on README.md
> +<button class='sbtn basic-btn blue-btn'> text </button>
remove the spacing around "text" and replace "text" with "Button" (Make this change on `index.html` as well)

2020-09-21 20:44 UTC, shahednasser commented on README.md
> +You can find all classes and their corresponding sButtons mentioned in our website.
Add a link to the website at "our website"

2020-09-21 20:44 UTC, shahednasser commented on README.md
> +This code will produce basic sButton with blue colour , same can be done for ```<a>``` tag
after "blue colour" put a period (.) instead of comma (same for `index.html`)

2020-09-22 08:07 UTC, salonigoyal2309 commented
@shahednasser this pull request is now having conflict with original repo , so what should I do ?

2020-09-22 16:47 UTC, shahednasser requested changes
Don't worry about the conflict. We'll resolve it once you make this last change!

2020-09-22 16:47 UTC, shahednasser commented on README.md
> +<a href='#' class='sbtn basic-btn blue-btn'>text</a>
Please change this to Button too. (same for index.html)

2020-09-22 17:46 UTC, merged

2020-09-22 17:46 UTC, shahednasser commented
Great thank you!

@all-contributors please add @salonigoyal2309 for code and documentation.