Hide Download button in the navbar when at the top of the page
shahednasser/sbuttons pull request #221
Opened 2020-09-26 02:11 UTC by Zuhdannur

Hello 🙌
I wanted to help this project

Issue: Hide Download button in the navbar when at the top of the page

2020-09-26 10:18 UTC, shahednasser commented
Hi @Zuhdannur I like your approach, but can you do it with css instead? basically it should be like `.navbar:not(.scrolling) .downloadIcon` display should be none, and for `.navbar.scrolling .downloadIcon` display should inline-block

2020-09-27 10:37 UTC, Zuhdannur commented
hi @shahednasser thanks for the reviews, you can check it newest commit

2020-09-27 14:33 UTC, shahednasser requested changes

2020-09-27 14:33 UTC, shahednasser commented on assets/js/index.js
> +      $(".downloadIcon").css('display','inline-block')
Change in this file is unnecessary now. Please change it back to how it was

2020-09-29 15:57 UTC, Zuhdannur commented
please check it again

2020-09-29 16:49 UTC, shahednasser requested changes
Can you please remove added files in ".idea" folder?

2020-10-01 17:36 UTC, merged