Added social round buttons
shahednasser/sbuttons pull request #255
Opened 2020-09-26 18:31 UTC by Neeraj3508

Issue:

2020-09-26 18:33 UTC, Neeraj3508 commented
@shahednasser you can now check it is showing no conflicts

2020-09-26 19:21 UTC, shahednasser requested changes
It all looks great, there's just one problem with the font. Previously, there was a rule in `assets/css/index.css` something like:
```
.social-btn {
font-family: 'Syne', sans-serif;
}
```

I'm not sure why it's gone now but please add it again.

2020-09-26 20:43 UTC, Neeraj3508 commented
@shahednasser you can check all the changes made + the one requested

2020-09-26 21:11 UTC, shahednasser requested changes

2020-09-26 21:11 UTC, shahednasser commented on assets/css/index.css
> +  font-family: 'Syne', sans-serif;
Please add "!important" to it as it is not applied.

2020-09-27 10:11 UTC, Neeraj3508 commented
@shahednasser done, added !important to index.html

2020-09-27 14:31 UTC, merged

2020-09-27 14:32 UTC, shahednasser commented
Great work thank you!

2020-09-27 18:10 UTC, Neeraj3508 commented
😊