done
shahednasser/sbuttons pull request #338
Opened 2020-09-30 19:58 UTC by Charu271

Issue:

2020-09-30 21:10 UTC, shahednasser requested changes
The buttons look good but I have a few remarks:

1. It seems you have a lot of repeated code in `_key.less` if you can refactor it to make sure there isn't a lot of repeated code then that would be great. If you're not sure how to do it, I can edit the file once other requested changes are implemented.
2. Please use for colors their associated variables in `src/sbuttons.less` instead of writing them directly.
3. Did you compile the code or just copy it into `dist/sbuttons.css`? You need to import `_key.less` in `src/components/_animated.less` then run `npm run compile`. You can't manually edit the `dist/sbuttons.css` file.

2020-09-30 21:10 UTC, shahednasser commented on src/components/animated/_key.less
> +  border-radius: 30px;
change `btn-rounded` to `rounded-btn`

2020-10-01 02:05 UTC, Charu271 commented
I will make all the required changes

2020-10-01 18:50 UTC, Charu271 commented
I have done all the changes you asked for but again facing issue while
making pull request as it is having conflicts

On Thu, 1 Oct 2020, 2:40 am Shahed Nasser, <notifications@github.com> wrote:

> *@shahednasser* requested changes on this pull request.
>
> The buttons look good but I have a few remarks:
>
>    1. It seems you have a lot of repeated code in _key.less if you can
>    refactor it to make sure there isn't a lot of repeated code then that would
>    be great. If you're not sure how to do it, I can edit the file once other
>    requested changes are implemented.
>    2. Please use for colors their associated variables in
>    src/sbuttons.less instead of writing them directly.
>    3. Did you compile the code or just copy it into dist/sbuttons.css?
>    You need to import _key.less in src/components/_animated.less then run npm
>    run compile. You can't manually edit the dist/sbuttons.css file.
>
> ------------------------------
>
> In src/components/animated/_key.less
> <https://github.com/shahednasser/sbuttons/pull/338#discussion_r497801405>:
>
> > +    box-shadow: inset 0px -8px 0px #341368;
> +  }
> +}
> +.key-btn.black-btn {
> +  border-top: 2px solid rgb(92, 82, 82);
> +  background-color: rgb(92, 82, 82);
> +  box-shadow: inset 0px -12px rgb(44, 40, 40);
> +  &:active {
> +    top: 2px;
> +    border-top: 2px solid #2b1800;
> +    background-color: rgb(71, 69, 69);
> +    box-shadow: inset 0px -8px 0px rgb(44, 40, 40);
> +  }
> +}
> +.key-btn.btn-rounded {
> +  border-radius: 30px;
>
> change btn-rounded to rounded-btn
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/shahednasser/sbuttons/pull/338#pullrequestreview-499813122>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOLEY7BVPWYN6ZZ4SWABGYDSIONENANCNFSM4R7QT6RQ>
> .
>

2020-10-01 18:55 UTC, shahednasser commented
You can make a pull request even if there are conflicts. You can also try to update your repo to the changes made in this one.

2020-10-01 19:19 UTC, Charu271 commented
I have created the pull request. Kindly go through it

On Fri, 2 Oct 2020, 12:25 am Shahed Nasser, <notifications@github.com>
wrote:

> You can make a pull request even if there are conflicts. You can also try
> to update your repo to the changes made in this one.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/shahednasser/sbuttons/pull/338#issuecomment-702332809>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOLEY7GARIOB7HDU2DP5SELSITGCLANCNFSM4R7QT6RQ>
> .
>

2020-10-01 20:00 UTC, closed without merging