Added Chat Box Button
shahednasser/sbuttons pull request #341
Opened 2020-09-30 20:14 UTC by dsnehasish74

![Screenshot (282)](https://user-images.githubusercontent.com/58779604/94734966-a3e38f80-0387-11eb-83c6-878534ad7ea3.png)

Issue:

2020-09-30 21:19 UTC, shahednasser requested changes
It all looks good, I just need you to make some changes requested below and also please check off the idea in the "button ideas" file

2020-09-30 21:19 UTC, shahednasser commented on assets/js/buttons-examples.js
> +          label: "chat Box Button",
Capitalize "chat" in label

2020-09-30 21:19 UTC, shahednasser commented on src/components/icon/_chat.less
> +.chat-btn {
add `transition: all .2s`

2020-09-30 21:19 UTC, shahednasser commented on src/components/icon/_chat.less
> +    box-shadow: 0px 1px 7px #4d4d4d;
change box-shadow color to `#838383`

2020-10-01 03:13 UTC, dsnehasish74 commented
All the changes are done ............... please kindly check this

2020-10-01 06:04 UTC, merged

2020-10-01 06:04 UTC, shahednasser commented
Great thank you!