removed box-shadow on clicking the animated button
shahednasser/sbuttons pull request #74
Opened 2020-09-10 18:27 UTC by shubhampandeyhld

animated button will no longer have the default box-shadow.

Issue: box-shadow on click button

2020-09-10 18:51 UTC, shahednasser requested changes
Hi there! I need the fix to be in the `src/components/animated/_click.less` file. Nothing in the assets files should be modified. Just add a `box-shadow: none;` to click buttons on `:active`

2020-09-10 19:06 UTC, shubhampandeyhld commented
I have made the changes

2020-09-10 19:48 UTC, shahednasser requested changes

2020-09-10 19:48 UTC, shahednasser commented on src/components/animated/_click.less
> +  .click-btn:active{
remove this

2020-09-10 19:48 UTC, shahednasser commented on src/components/animated/_click.less
>    &:active {
Change this to:
```
&:active,
&:focus
```

2020-09-10 19:48 UTC, shahednasser commented on assets/js/index.js
> +$.fn.isOnScreen = function(){
This entire file shouldn't be changed. You can return it to how it was with `git checkout assets/js/index.js`

2020-09-10 19:48 UTC, shahednasser commented on assets/css/index.css
> +
This file shouldn't be changed. Return it to how it was with `git checkout assets/css/index.css`

2020-09-11 04:31 UTC, shubhampandeyhld commented
I need again forked the repo. because its saying your branch is up to date with master

2020-09-11 14:28 UTC, shahednasser commented
closed by #75

2020-09-11 14:28 UTC, closed without merging